print("  EEEEEEEEEEEE      VV        VV      HH        HH")
print("  EEEEEEEEEEEE      VV       VV       HH        HH")
print("  EE                 VV     VV        HH        HH")
print("  EE                 VV     VV        HH        HH")
print("  EEEEEEEEEEEE        VV   VV         HHHHHHHHHHHH")
print("  EEEEEEEEEEEE        VV   VV         HHHHHHHHHHHH")
print("  EE                   VV VV          HH        HH")
print("  EE                   VV VV          HH        HH")
print("  EEEEEEEEEEEE    ..    VVVV      ..  HH        HH")
print("  EEEEEEEEEEEE    ..     VV       ..  HH        HH")     

